id: d65d6b63710c4d279b4b0d97d893d7f8
initial_creation_type: ocr
source_metadata:
  volumes:
    0bfefc92955446128219667526de9679:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
